### PR TITLE
Narrow Neal import to the simulated annealing module

### LINKED ISSUE #9: Testing failure for incomplete conda environment
When testing package we get error
`ERROR: LoadError: InitError: Python: ModuleNotFoundError: No module named 'pkg_resources'`
which suggests that the conda environment needs a version of setuptools for it to work.

### PR DESCRIPTION
**Pull request by bernalde**
This replaces the earlier setuptools attempt for #9 with a fix that matches the old CI traceback.

The January failing jobs were not caused by missing pkg_resources. They failed while importing dwave.samplers because dwave.samplers.random.cyrandom raised AttributeError: module 'numpy.random.bit_generator' has no attribute 'SeedlessSequence' during DWave.Neal initialization.

This PR narrows the wrapper import from dwave.samplers to dwave.samplers.sa.sampler, which is the only module the Julia Neal wrapper actually uses. That keeps unrelated sampler modules out of the import path and avoids the failure surface from the old CI run.

It also adds a regression test that checks the wrapper binds to dwave.samplers.sa.sampler.

Scope note:
- This PR only fixes the Neal import path and initialization failure.
- Broader support for the other classical samplers in `dwave.samplers` remains follow-up work in #17.

Testing:
- JULIA_DEPOT_PATH=$PWD/.julia-depot:$HOME/.julia julia --project=. -e 'using Pkg; Pkg.test()'

Fixes #9

### CODE REVIEW

File: src/neal/sampler.jl [hunk 1]
```diff
@@ -12,8 +12,10 @@ const dwave_samplers = PythonCall.pynew() # initially NULL
 
 function __init__()
     PythonCall.pycopy!(np, pyimport("numpy"))
-    # Note: 'neal' package was deprecated and replaced by 'dwave.samplers' in dwave-ocean-sdk 8.0+
-    PythonCall.pycopy!(dwave_samplers, pyimport("dwave.samplers"))
+    # Note: 'neal' package was deprecated and replaced by 'dwave.samplers' in
+    # dwave-ocean-sdk 8.0+. Import only the simulated annealing module we use,
+    # so unrelated sampler imports cannot break `DWave.Neal` initialization.
+    PythonCall.pycopy!(dwave_samplers, pyimport("dwave.samplers.sa.sampler"))
```
Comment (bernalde) [inline src/neal/sampler.jl]: This still executes `dwave.samplers.__init__`. I verified locally with `importlib.import_module("dwave.samplers.sa.sampler")`, and `dwave.samplers.random` is present in `sys.modules` afterwards. Since `dwave/samplers/__init__.py` eagerly imports `random`, `sa`, `sqa`, and the other sampler packages, the old `random.cyrandom` failure path from https://github.com/JuliaQUBO/DWave.jl/actions/runs/20728303486 is still reachable here. This needs either a real package-bypass import mechanism or a version constraint that removes the bad dependency combination.

File: test/neal_parity.jl [hunk 2]
```diff
@@ -135,6 +135,12 @@ function _wrapper_neal_error(h::Vector{Float64}, J::Matrix{Float64}; kwargs...)
     end
 end
 
+Test.@testset "Neal imports only the simulated annealing module" begin
```
Comment (bernalde) [inline test/neal_parity.jl]: This test only checks the module name, so it still passes even though the import path pulls in `dwave.samplers.random` as a side effect. Please make the regression cover the actual failure surface, ideally in a fresh Python process or after clearing the relevant `sys.modules` entries, and assert that initializing `DWave.Neal` does not touch the unrelated `random` sampler.

**Review by bernalde — COMMENTED** [review]
I reran `Pkg.test()` locally on this branch and the suite passes, and the PR CI is green on both Ubuntu and Windows. The problem is that a targeted Python import check still shows the same side effect that caused the January failure: `importlib.import_module("dwave.samplers.sa.sampler")` still executes `dwave.samplers.__init__`, which leaves `dwave.samplers.random` loaded. Because `dwave/samplers/__init__.py` eagerly imports `random`, this change does not actually remove the old `random.cyrandom` failure surface from https://github.com/JuliaQUBO/DWave.jl/actions/runs/20728303486 . I think this needs one more revision before merge.

File: test/neal_parity.jl (hunk 2 above)
Comment (bernalde) [reply test/neal_parity.jl]: Addressed in [3ec24ff](https://github.com/JuliaQUBO/DWave.jl/commit/3ec24ff2e3e8c5c4f307ecde140161417e7abc60).

I replaced the module-name-only check with a stronger regression in [test/neal_parity.jl](https://github.com/JuliaQUBO/DWave.jl/blob/3ec24ff2e3e8c5c4f307ecde140161417e7abc60/test/neal_parity.jl). The test now clears the `dwave.samplers` entries from `sys.modules`, reruns `DWave.Neal.__init__()`, and asserts that:

- `dwave.samplers.sa.sampler` and `dwave.samplers.sa.simulated_annealing` are loaded
- `dwave.samplers.random` is not loaded

That makes the regression cover the actual bug surface rather than only the imported module name.

File: src/neal/sampler.jl (hunk 1 above)
Comment (bernalde) [reply src/neal/sampler.jl]: Addressed in [3ec24ff](https://github.com/JuliaQUBO/DWave.jl/commit/3ec24ff2e3e8c5c4f307ecde140161417e7abc60).

I replaced the ineffective `pyimport("dwave.samplers.sa.sampler")` call with a helper in [src/neal/sampler.jl](https://github.com/JuliaQUBO/DWave.jl/blob/3ec24ff2e3e8c5c4f307ecde140161417e7abc60/src/neal/sampler.jl) that constructs lightweight `dwave.samplers` and `dwave.samplers.sa` package objects in `sys.modules` and then imports `dwave.samplers.sa.sampler` without executing `dwave.samplers.__init__`.

That change avoids loading `dwave.samplers.random` during `DWave.Neal` initialization, which was the failure surface called out in the old CI traceback.

File: src/neal/sampler.jl [hunk 3]
```diff
@@ -9,11 +9,105 @@ using PythonCall
 # -*- :: Python D-Wave Simulated Annealing :: -*- #
 const np = PythonCall.pynew() # initially NULL
 const dwave_samplers = PythonCall.pynew() # initially NULL
+const dwave_samplers_import_mode = Ref{Symbol}(:uninitialized)
+
```
Comment (bernalde) [inline src/neal/sampler.jl:22]: The `dwave_samplers_import_mode` variable is a useful debugging aid, but it is not documented. Consider adding a docstring or comment explaining its purpose and the meaning of each mode (`:narrow`, `:fallback`, `:uninitialized`).

File: src/neal/sampler.jl [hunk 4]
```diff
@@ -9,11 +9,105 @@ using PythonCall
...
+""",
+        @__MODULE__,
+        (
+            dwave = pyimport("dwave"),
+            sys = pyimport("sys"),
+        ),
+    )
+
+    return nothing
+end
```
Comment (bernalde) [inline src/neal/sampler.jl:47]: This function is exported for testing but lacks a docstring. Since it manipulates Python's `sys.modules` directly, consider adding a warning comment that calling this function outside of tests can leave the module in an inconsistent state.

File: src/neal/sampler.jl [hunk 5]
```diff
@@ -9,11 +9,105 @@ using PythonCall
...
+        importlib = pyimport("importlib"),
+        pathlib = pyimport("pathlib"),
+        sys = pyimport("sys"),
+    )
+
+    ans = PythonCall.pyexec(
+        @NamedTuple{sampler::PythonCall.Py},
+        """
+root = pathlib.Path(next(iter(dwave.__path__)))
+samplers_name = "dwave.samplers"
```
Comment (bernalde) [inline src/neal/sampler.jl:65]: This assumes `dwave.__path__` is non-empty. While this should always be true for an installed package, consider adding a guard or documenting this assumption explicitly. If dwave is somehow installed in a non-standard way where `__path__` is empty, this will raise a `StopIteration` that may be confusing to debug.

File: src/neal/sampler.jl [hunk 6]
```diff
@@ -9,11 +9,105 @@ using PythonCall
...
+samplers_pkg = sys.modules.get(samplers_name)
+if samplers_pkg is None:
+    samplers_spec = importlib.util.spec_from_file_location(
+        samplers_name,
+        root / "samplers" / "__init__.py",
+        submodule_search_locations=[str(root / "samplers")],
+    )
+    samplers_pkg = importlib.util.module_from_spec(samplers_spec)
+    sys.modules[samplers_name] = samplers_pkg
+
```
Comment (bernalde) [inline src/neal/sampler.jl:80]: The spec is created with the init file path but `spec.loader.exec_module` is never called on `samplers_pkg`. This is intentional to avoid pulling in unrelated samplers, but a brief comment explaining why the init is skipped here (and on `sa_pkg`) would help future maintainers understand this is deliberate.

File: src/neal/sampler.jl [hunk 7]
```diff
@@ -9,11 +9,105 @@ using PythonCall
...
-    PythonCall.pycopy!(dwave_samplers, pyimport("dwave.samplers"))
+    # Note: 'neal' package was deprecated and replaced by 'dwave.samplers' in
+    # dwave-ocean-sdk 8.0+. Load the simulated annealing submodule directly so
+    # we do not execute dwave.samplers.__init__ and pull in unrelated samplers.
+    if Sys.iswindows()
+        # On Windows, the compiled simulated_annealing extension only imports
+        # reliably through Python's standard package path.
+        _clear_sa_import_state!()
+        PythonCall.pycopy!(dwave_samplers, pyimport("dwave.samplers"))
+        dwave_samplers_import_mode[] = :fallback
```
Comment (bernalde) [inline src/neal/sampler.jl]: The Windows fallback path calls `_clear_sa_import_state!()` before the standard import. Consider adding a comment explaining why this clearing is necessary here: it ensures any prior partial import state from a previous session does not interfere with the standard import.

File: test/neal_parity.jl [hunk 8]
```diff
@@ -135,6 +135,87 @@ function _wrapper_neal_error(h::Vector{Float64}, J::Matrix{Float64}; kwargs...)
     end
 end
 
+function _reset_neal_python_modules!()
+    DWave.Neal._clear_sa_import_state!()
+    DWave.Neal.__init__()
+
+    return nothing
+end
```
Comment (bernalde) [inline test/neal_parity.jl:144]: This helper calls `__init__()` without error handling. If `__init__()` fails during a test, the test will abort rather than producing a clear diagnostic. Consider wrapping the `__init__()` call or documenting that test failures here indicate a broken import path.

File: test/neal_parity.jl [hunk 9]
```diff
@@ -135,6 +135,87 @@ function _wrapper_neal_error(h::Vector{Float64}, J::Matrix{Float64}; kwargs...)
...
+    if DWave.Neal.dwave_samplers_import_mode[] == :narrow
+        Test.@test DWave.Neal.PythonCall.pyconvert(String, DWave.Neal.dwave_samplers.__name__) ==
+            "dwave.samplers.sa.sampler"
+        Test.@test !_sys_modules_contains("dwave.samplers.random")
+    else
+        Test.@test DWave.Neal.dwave_samplers_import_mode[] == :fallback
+        Test.@test DWave.Neal.PythonCall.pyconvert(String, DWave.Neal.dwave_samplers.__name__) ==
+            "dwave.samplers"
+    end
+end
```
Comment (bernalde) [inline test/neal_parity.jl:220]: The test correctly validates both the narrow and fallback import modes. However, the test does not verify that the `SimulatedAnnealingSampler` can actually perform sampling. Consider adding a minimal sampling call to ensure the imported module is fully functional.

File: test/neal_parity.jl [hunk 10]
```diff
@@ -135,6 +135,87 @@ function _wrapper_neal_error(h::Vector{Float64}, J::Matrix{Float64}; kwargs...)
...
+
+Test.@testset "Neal initialization repairs broken sampler cache state" begin
+    _inject_broken_sa_sampler!()
+    DWave.Neal.__init__()
+
+    Test.@test DWave.Neal.PythonCall.pyconvert(String, DWave.Neal.dwave_samplers.__name__) in
+        ("dwave.samplers.sa.sampler", "dwave.samplers")
+    Test.@test DWave.Neal.dwave_samplers.SimulatedAnnealingSampler !== nothing
+    Test.@test DWave.Neal.dwave_samplers_import_mode[] in (:narrow, :fallback)
+end
```
Comment (bernalde) [inline test/neal_parity.jl:239]: This test verifies recovery from a broken cache state but does not verify that sampling actually works after recovery. Consider adding a minimal sampling assertion to confirm the repaired module is functional.

**Review by bernalde — COMMENTED** [review]
**Overall Assessment: Approve with minor suggestions**

The PR correctly addresses issue #9 by implementing a custom import mechanism that loads only `dwave.samplers.sa.sampler` without executing `dwave.samplers.__init__`, which avoids the `random.cyrandom` failure surface. All tests pass, and the implementation properly handles the Windows fallback case.

**Test Verification Summary**

All tests pass on Linux:
- Neal initialization loads the simulated annealing sampler: 9/9
- Neal initialization repairs broken sampler cache state: 3/3
- Neal parity with direct dwave.samplers: 2/2
- Neal wrapper seed determinism: 1/1
- Neal wrapper schedule validation: 6/6
- Neal parity with sparse support: 2/2

The narrow import correctly avoids loading `dwave.samplers.random` (verified manually).

**Recommendation**: Merge after addressing the minor suggestions in the inline comments. The core implementation is sound and the tests adequately cover the failure scenarios described in issue #9.

File: src/neal/sampler.jl [hunk 11]
```diff
@@ -9,11 +9,105 @@ using PythonCall
...
+        samplers_name,
+        root / "samplers" / "__init__.py",
+        submodule_search_locations=[str(root / "samplers")],
+    )
+    samplers_pkg = importlib.util.module_from_spec(samplers_spec)
+    sys.modules[samplers_name] = samplers_pkg
+
+dwave.samplers = samplers_pkg
+
+sa_pkg = sys.modules.get(sa_name)
```
Comment (bernalde) [inline src/neal/sampler.jl]: This only repairs the leaf `dwave.samplers.sa.sampler` module. If `dwave.samplers` or `dwave.samplers.sa` are already present in `sys.modules` with a bad `__path__`, we reuse them unchanged, and `spec.loader.exec_module(sampler)` still fails to resolve `dwave.samplers.sa.simulated_annealing`. I reproduced that in a clean Python process with the same `types.ModuleType(...); __path__ = []` state that the test injects below. Please rebuild or validate the parent packages here before importing the sampler.

File: src/neal/sampler.jl [hunk 12]
```diff
@@ -9,11 +9,105 @@ using PythonCall
...
-    # Note: 'neal' package was deprecated and replaced by 'dwave.samplers' in dwave-ocean-sdk 8.0+
-    PythonCall.pycopy!(dwave_samplers, pyimport("dwave.samplers"))
+    # Note: 'neal' package was deprecated and replaced by 'dwave.samplers' in
+    # dwave-ocean-sdk 8.0+. Load the simulated annealing submodule directly so
+    # we do not execute dwave.samplers.__init__ and pull in unrelated samplers.
+    if Sys.iswindows()
+        # On Windows, the compiled simulated_annealing extension only imports
+        # reliably through Python's standard package path.
+        _clear_sa_import_state!()
+        PythonCall.pycopy!(dwave_samplers, pyimport("dwave.samplers"))
```
Comment (bernalde) [inline src/neal/sampler.jl]: This Windows branch goes back through `pyimport("dwave.samplers")`, which executes `dwave.samplers.__init__` and eagerly imports `dwave.samplers.random`, `sqa`, and the other sampler packages. Upstream `__init__.py` does that unconditionally: https://github.com/dwavesystems/dwave-samplers/blob/1.6.0/dwave/samplers/__init__.py . That reopens the same `random.cyrandom` surface this PR is trying to avoid, so I do not think issue `#9` is actually closed on Windows with this fallback.

File: test/neal_parity.jl [hunk 13]
```diff
@@ -135,6 +135,87 @@ function _wrapper_neal_error(h::Vector{Float64}, J::Matrix{Float64}; kwargs...)
...
 
+function _reset_neal_python_modules!()
+    DWave.Neal._clear_sa_import_state!()
+    DWave.Neal.__init__()
+
+    return nothing
+end
+
+function _inject_broken_sa_sampler!()
+    DWave.Neal._clear_sa_import_state!()
```
Comment (bernalde) [inline test/neal_parity.jl:147]: This regression is still running with `dwave.samplers.sa.simulated_annealing` already resident in `sys.modules`, because `_clear_sa_import_state!()` never removes that extension module. That is why the test passes even though the clean-process reproduction above still fails when the parent packages have `__path__ = []`. Please clear `dwave.samplers.sa.simulated_annealing` as well or run this case in a fresh interpreter so the broken-cache repair is exercised for real.

**Review by bernalde — COMMENTED** [review]
I reran `JULIA_DEPOT_PATH=$PWD/.julia-depot:$HOME/.julia julia --project=. -e 'using Pkg; Pkg.test()'` on Linux and the suite passes. I also exercised the new import path directly with the project Python environment under `.CondaPkg/.pixi/envs/default/bin/python`. Those targeted checks still found two functional gaps, so I think this needs one more revision before merge. GitHub does not allow the PR author to submit `REQUEST_CHANGES`, so I am leaving the requested revisions as inline review comments instead.

File: src/neal/sampler.jl (hunk 1 above)
Comment (bernalde) [reply src/neal/sampler.jl]: Addressed in [d503a95](https://github.com/JuliaQUBO/DWave.jl/commit/d503a957054aedd4cd490d0b7b0aed61f8117b25). The later Windows fallback reopened this path, so I removed that fallback and now always rebuild a clean `dwave.samplers` package tree before importing only `dwave.samplers.sa.sampler` in [src/neal/sampler.jl](https://github.com/JuliaQUBO/DWave.jl/blob/d503a957054aedd4cd490d0b7b0aed61f8117b25/src/neal/sampler.jl). That keeps `dwave.samplers.random` out of `sys.modules` again.

File: src/neal/sampler.jl (hunk 3 above)
Comment (bernalde) [reply src/neal/sampler.jl:22]: Addressed in [d503a95](https://github.com/JuliaQUBO/DWave.jl/commit/d503a957054aedd4cd490d0b7b0aed61f8117b25). I added a docstring to `dwave_samplers_import_mode` in [src/neal/sampler.jl](https://github.com/JuliaQUBO/DWave.jl/blob/d503a957054aedd4cd490d0b7b0aed61f8117b25/src/neal/sampler.jl) and reduced the state space to the modes that remain after this fix: `:uninitialized` and `:narrow`.

File: test/neal_parity.jl (hunk 2 above)
Comment (bernalde) [reply test/neal_parity.jl]: Addressed in [d503a95](https://github.com/JuliaQUBO/DWave.jl/commit/d503a957054aedd4cd490d0b7b0aed61f8117b25). The regression in [test/neal_parity.jl](https://github.com/JuliaQUBO/DWave.jl/blob/d503a957054aedd4cd490d0b7b0aed61f8117b25/test/neal_parity.jl) now clears the full `dwave.samplers` module subtree, checks that `dwave.samplers.random` stays unloaded, and performs a minimal sampling call after initialization so the import path is tested functionally rather than only by module name.

File: src/neal/sampler.jl (hunk 4 above)
Comment (bernalde) [reply src/neal/sampler.jl:47]: Addressed in [d503a95](https://github.com/JuliaQUBO/DWave.jl/commit/d503a957054aedd4cd490d0b7b0aed61f8117b25). `_clear_sa_import_state!()` now has a docstring in [src/neal/sampler.jl](https://github.com/JuliaQUBO/DWave.jl/blob/d503a957054aedd4cd490d0b7b0aed61f8117b25/src/neal/sampler.jl) that explains both its purpose and the fact that it mutates Python `sys.modules` and is intended only for initialization and tests.

File: src/neal/sampler.jl (hunk 5 above)
Comment (bernalde) [reply src/neal/sampler.jl:65]: Addressed in [d503a95](https://github.com/JuliaQUBO/DWave.jl/commit/d503a957054aedd4cd490d0b7b0aed61f8117b25). `_import_sa_sampler()` now guards `dwave.__path__` in [src/neal/sampler.jl](https://github.com/JuliaQUBO/DWave.jl/blob/d503a957054aedd4cd490d0b7b0aed61f8117b25/src/neal/sampler.jl) and raises `ImportError("dwave package does not define an import path")` instead of failing with a bare `StopIteration`.

File: src/neal/sampler.jl (hunk 6 above)
Comment (bernalde) [reply src/neal/sampler.jl:80]: Addressed in [d503a95](https://github.com/JuliaQUBO/DWave.jl/commit/d503a957054aedd4cd490d0b7b0aed61f8117b25). I added explicit comments in [src/neal/sampler.jl](https://github.com/JuliaQUBO/DWave.jl/blob/d503a957054aedd4cd490d0b7b0aed61f8117b25/src/neal/sampler.jl) explaining that the parent package specs are created only to provide valid search paths and that their `__init__` files are intentionally not executed because they eagerly import unrelated samplers.

File: src/neal/sampler.jl (hunk 7 above)
Comment (bernalde) [reply src/neal/sampler.jl]: Addressed in [d503a95](https://github.com/JuliaQUBO/DWave.jl/commit/d503a957054aedd4cd490d0b7b0aed61f8117b25). I removed the Windows fallback entirely and replaced it with a single clean-state rebuild path in [src/neal/sampler.jl](https://github.com/JuliaQUBO/DWave.jl/blob/d503a957054aedd4cd490d0b7b0aed61f8117b25/src/neal/sampler.jl), with a comment explaining why `_clear_sa_import_state!()` runs before the narrow import.

File: test/neal_parity.jl (hunk 9 above)
Comment (bernalde) [reply test/neal_parity.jl:220]: Addressed in [d503a95](https://github.com/JuliaQUBO/DWave.jl/commit/d503a957054aedd4cd490d0b7b0aed61f8117b25). The initialization test in [test/neal_parity.jl](https://github.com/JuliaQUBO/DWave.jl/blob/d503a957054aedd4cd490d0b7b0aed61f8117b25/test/neal_parity.jl) now calls `_assert_neal_sampler_works()`, which performs a minimal `SimulatedAnnealingSampler().sample_ising(...)` run after the import assertions.

File: test/neal_parity.jl (hunk 8 above)
Comment (bernalde) [reply test/neal_parity.jl:144]: Addressed in [d503a95](https://github.com/JuliaQUBO/DWave.jl/commit/d503a957054aedd4cd490d0b7b0aed61f8117b25). I kept the raw exception path because it is the most useful failure signal in a test run, but I documented that intent directly above `_reset_neal_python_modules!()` in [test/neal_parity.jl](https://github.com/JuliaQUBO/DWave.jl/blob/d503a957054aedd4cd490d0b7b0aed61f8117b25/test/neal_parity.jl) so a failure there is clearly identified as a broken Neal import path.

File: src/neal/sampler.jl (hunk 12 above)
Comment (bernalde) [reply src/neal/sampler.jl]: Addressed in [d503a95](https://github.com/JuliaQUBO/DWave.jl/commit/d503a957054aedd4cd490d0b7b0aed61f8117b25). I removed the Windows branch that went through `pyimport("dwave.samplers")` and now use the same narrow import path everywhere in [src/neal/sampler.jl](https://github.com/JuliaQUBO/DWave.jl/blob/d503a957054aedd4cd490d0b7b0aed61f8117b25/src/neal/sampler.jl). That closes the `dwave.samplers.__init__` path that was still importing `random` on Windows.

File: test/neal_parity.jl (hunk 13 above)
Comment (bernalde) [reply test/neal_parity.jl:147]: Addressed in [d503a95](https://github.com/JuliaQUBO/DWave.jl/commit/d503a957054aedd4cd490d0b7b0aed61f8117b25). `_clear_sa_import_state!()` now removes the entire `dwave.samplers` subtree, including `dwave.samplers.sa.simulated_annealing`, and the regression in [test/neal_parity.jl](https://github.com/JuliaQUBO/DWave.jl/blob/d503a957054aedd4cd490d0b7b0aed61f8117b25/test/neal_parity.jl) now checks sampling after repair so the stale-module masking from this comment cannot slip through again.

File: src/neal/sampler.jl (hunk 11 above)
Comment (bernalde) [reply src/neal/sampler.jl]: Addressed in [d503a95](https://github.com/JuliaQUBO/DWave.jl/commit/d503a957054aedd4cd490d0b7b0aed61f8117b25). `DWave.Neal.__init__()` now clears the full `dwave.samplers` module tree before rebuilding the narrow import, and `_import_sa_sampler()` always recreates both parent packages with the correct package search paths in [src/neal/sampler.jl](https://github.com/JuliaQUBO/DWave.jl/blob/d503a957054aedd4cd490d0b7b0aed61f8117b25/src/neal/sampler.jl). That makes the broken parent-package state from this comment recover correctly.

File: test/neal_parity.jl (hunk 10 above)
Comment (bernalde) [reply test/neal_parity.jl:239]: Addressed in [d503a95](https://github.com/JuliaQUBO/DWave.jl/commit/d503a957054aedd4cd490d0b7b0aed61f8117b25). The broken-cache recovery test in [test/neal_parity.jl](https://github.com/JuliaQUBO/DWave.jl/blob/d503a957054aedd4cd490d0b7b0aed61f8117b25/test/neal_parity.jl) now also calls `_assert_neal_sampler_works()`, so it verifies that repair restores actual sampling, not only symbol lookup.

**Comment by bernalde** [comment]
I pushed [d503a95](https://github.com/JuliaQUBO/DWave.jl/commit/d503a957054aedd4cd490d0b7b0aed61f8117b25) to address the remaining review feedback on this PR. The branch now rebuilds the `dwave.samplers` package tree from a clean Python state, removes the Windows fallback through `dwave.samplers.__init__`, documents the import-state helpers, and hardens the Neal regression tests so they verify both import isolation and a minimal sampling call after initialization and broken-cache repair. That covers the non-threaded review bodies at [4025903084](https://github.com/JuliaQUBO/DWave.jl/pull/19#pullrequestreview-4025903084), [4057468425](https://github.com/JuliaQUBO/DWave.jl/pull/19#pullrequestreview-4057468425), and [4057487881](https://github.com/JuliaQUBO/DWave.jl/pull/19#pullrequestreview-4057487881). The concrete file-by-file details are in the inline thread replies.
